/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as ConversacionesRouteImport } from './routes/conversaciones'
import { Route as IndexRouteImport } from './routes/index'

const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversacionesRoute = ConversacionesRouteImport.update({
  id: '/conversaciones',
  path: '/conversaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conversaciones': typeof ConversacionesRoute
  '/pipeline': typeof PipelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conversaciones': typeof ConversacionesRoute
  '/pipeline': typeof PipelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conversaciones': typeof ConversacionesRoute
  '/pipeline': typeof PipelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/conversaciones' | '/pipeline'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/conversaciones' | '/pipeline'
  id: '__root__' | '/' | '/conversaciones' | '/pipeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConversacionesRoute: typeof ConversacionesRoute
  PipelineRoute: typeof PipelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversaciones': {
      id: '/conversaciones'
      path: '/conversaciones'
      fullPath: '/conversaciones'
      preLoaderRoute: typeof ConversacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConversacionesRoute: ConversacionesRoute,
  PipelineRoute: PipelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
